### ISSUE TITLE
Feature Request: view option

### ISSUE THREAD

**Issue by Morriz** [chrisgrieser/alfred-homebrew#3]
### Feature Requested

Just viewing the page for a package would be nice, so we can read more...

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
You can already open the package's homepage via `cmd+enter`

**Comment by Morriz** [comment]
aha...I see the readme has that info...would it be possible to have it in the UI like commands from others?

**Comment by Morriz** [comment]
I meant to show it inline, not present links to a page we have to open. But hey, I can live with this ;) Thanks

**Comment by chrisgrieser** [comment]
you'd have to be a bit more specific what you mean by "show it inline", otherwise it's hard to understand what you mean. That's why the Feature Request form asks for screenshots ;)

**Comment by Morriz** [comment]
Let me turn it around in a question

If an extra option (bs?) would be available to just show info that the package publishes, then what would your plugin show?

**Comment by chrisgrieser** [comment]
I have no idea what you are asking here. 

Could you *please* show an annotated screenshot, example, diagram etc. what you'd like to have? Otherwise, I am afraid I am not able to do anything, since one-line-descriptions with some vague reference to "package info" are just not specific enough for me to be able to follow.

**Comment by Morriz** [comment]
It's ok...I rest my effort...tnx for your patience
